### PR TITLE
Added quotes to service-paths

### PR DESCRIPTION
**Pull request by Svenfa**
Added quotes to binaryPathName. Otherwise windows wouldn't start the service if there were any spaces in it.

### CODE REVIEW

**Comment by tsg** [comment]
Hi @Svenfa, thank you for your contribution, can you sign our [CLA](https://www.elastic.co/contributor-agreement/), please?

**Comment by Svenfa** [comment]
Hi @tsg, thanks for the hint. It's done!

**Comment by ruflin** [comment]
@Svenfa Thanks for the contribution.

**Comment by dedemorton** [comment]
@ruflin When will this fix be available in the product? Right now, if users follow the steps in the getting started guide(s) and install on Windows under C:\Program Files, they run into this issue when they try to start the service. Should I document the workaround in the GS (editing the script to add quotes to the paths), or wait until the fix is available in the product?

**Comment by ruflin** [comment]
@dedemorton We should make this available with 1.0.1, so quite soon. I would not invest time to document it.

**Pull request merged**
